---
title: "Sensitivity"
author: "Remo Schmutz"
date: "2023-09-02"
output: pdf_document
---

TODO:

-   Update logic for treatement

-   Update preprocessing in general

This document serves as an overview of the assumptions made during preprocessing and analysis. This gives us a basis for the multiverse analysis.

## Preprocessing

### General

-   prevalent TB: TB date +- 60 days of ART start date.

-   recent TB: TB date between 360 and 60 days before ART start.

-   presenting TB: prevalent or recent TB

-   Use tbd_pat_birth and region to create region_born

-   Create cd4_baseline and rna_baseline using the closest non-NA measurement inbetween 180 days before and 30 days after ART start.

-   grouping baseline values:

    -   CD4: '0-99', '100-349' and '350+'

    -   Viral Load: '0-999', '1,000-9,999' and '10,000+'

-   WHO-stages: using the dis.dta and which has 57,073 rows containing dates and diagnosed diseases (multiple rows per ID) and var_disease which states the CDC category for each disease. I then see what diagnosis was closest to the ART start up to 30 days after ART start and use this as the CDC category. Here I could possibly check for the highest category in a certain interval. I then use [this](https://www.cdc.gov/mmwr/preview/mmwrhtml/rr5710a3.htm) transformation to get the WHO-stage.

-   CD4 and viral-load at TB diagnosis using the closest non-NA measurement inbetween 180 days before and 15 days after ART start.

-   last_persontime: I create this variable for the time-to-Incidence Ananlysis. If the person died, I calculate the days between ART start and death date. If else, I use the difference between last follow-up date and ART start.

-   Treatment at ART start: I use the modif.dta file which includes treatments at different times. There are multiple rows per ID. For every ID I use the treatment that is closest to ART start. Note: There are several IDs which have the same moddate and enddate (i.e. the started and ended the treatment at the same time). I didn't exclude these. I then use the following code to define the regimen:

    ``` r
    regimen = case_when(
          is.na(num_inti) & is.na(num_nnrti) & is.na(num_pi) ~ "unknown",
          num_pi != 0 ~ "PI-based",
          num_nnrti != 0 & num_inti != 0 ~ "Other",
          num_nnrti != 0 ~ "NNRTI-based",
          num_inti != 0 ~ "INSTI-based",
          TRUE ~ "Other"
        )
    ```

-   Tb drug resistance: If any of tbd_drug_resist_1:tbd_drug_resist_99 are checked, I mark as drug resistant.

-   TB treatment: Use the med_drug.dta file. I check which meds have been taken inbetween 5 days before and 60 days after ART start. If any of INH, RIF, EMB, PYZ where used I assign "standard". For every ID I check if there was a "standard"-drug used in this timeframe I use "standard", else I use "Other".

### Suppression

-   Thresholds:

    -   CD4: 400

    -   Viral-load: 350

-   For every ID I check every measurement and define suppression date as the date where two measurements after another are below/over the threshold. Note: I didn't exclude NAs, meaning that I probably overerstimate the time until non-/suppression. There could potentially be NAs that prevent two consecutive measurements to meet the threshold. I'll probably change this anyway for the main analysis. The problem is, if I want to simunanously check VL and CD4, I'm not sure how i would code that, because there might be some NA for VL and not CD4 and vise-versa. I then use the first suppression date only. I add persontime_years.suppression as time until viral suppression from ART start, if viral-suppression wasn't achieved I use time until death, I patient didn't die I use time until last follow-up (analog for non-suppression).

## Analysis

### Incidence

-   
